version: "3.8"
services:
  ffmpeg-api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    # Give the container access to Intel iGPU
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    restart: unless-stopped

  # Hot-reload profile for dev
  ffmpeg-api-dev:
    build: .
    profiles: ["dev"]
    command: python -m uvicorn video_main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file: .env
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - .:/app
