version: "3.8"
services:
  ffmpeg-api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    # volumes:
    #   - ./watermark.png:/app/watermark.png:ro
    restart: unless-stopped

  ffmpeg-api-dev:
    build: .
    profiles: ["dev"]
    command: python -m uvicorn video_main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
